stages:
  - setup
  - build
  - test
  - lint
  - report

default:
  image: node:16.14.2
  before_script:
    - cd client

setup:install:
  stage: setup
  script:
    - "yarn"
  artifacts:
    paths:
      - client/node_modules/
    expire_in: 1 hour

build:app:
  stage: build
  needs:
    - job: setup:install
      artifacts: true
  script:
    - "yarn run build"

test:unit-test:
  stage: test
  needs:
    - job: setup:install
      artifacts: true
  script:
    - "yarn run test"

lint:app:
  stage: lint
  needs:
    - job: setup:install
      artifacts: true
  script:
    - "npm run lint"
